### ISSUE TITLE
Invalid CFML construct found on line 63 at column 41.

### ISSUE THREAD

**Issue by Klodovsky** [rewingNL/pythonforword#1]
![image](https://user-images.githubusercontent.com/55706752/99394633-1d532500-28d7-11eb-9be9-5f6217ab3c81.png)

is this caused by not finding the .bat file ? 

I'm using windows 10 & Python 3.7 , CF 2018

**Comment by sebgmc** [comment]
@Klodovskyy this is an ACF issue - it works this way in Lucee 4.5+. Please try and add comma's between the params or read the explanation here: https://cfdocs.org/cfexecute

**Comment by Klodovsky** [comment]
@sebgmc  Yes sir I'm using CF 2018 and it's a syntax error I have fixed it thanks ! might help out future users of this repo .

Another error I'm getting is that the JSONFILE is already defined in arguments, is this version problem as well ? 

![image](https://user-images.githubusercontent.com/55706752/99400370-cbae9880-28de-11eb-9d86-a8dbebcb68f7.png)

**Comment by sebgmc** [comment]
@Klodovskyy ok, that is weird, this just works on Lucee ;-) Try changing the name of the `var jsonFile` into something like `var jsonFileLocal`. And further references down the line in the code of course. If this is ACF2018 way-of-working, you'll probably get the same issue with the other local var that is also an argument: `docStruct`. Preferably the other two params set atop the function-code can be set in the argument-definition instead as default values.
It may also be that the local-scope is not automagically set in ACF 2018. In Lucee you can choose how the local scope in a function is invoked. So in your case you could do `var local.jsonFile` instead and then use the local-scope when referenceing the variable in the rest of the function. Then ACF knows which "version" of the variable to use instead of guessing.

**Comment by rewingNL** [comment]
Made several modifications to 'pythonforwordservice.cfc' to make it work on both Lucee and Coldfusion server

**Comment by rewingNL** [comment]
Refactory of service has been done
